storePassword=NEPSTRALIA@!23--11123
keyPassword=8499NEPSTRALIA@11123--@!23
keyAlias=NEPSTRALIA
storeFileSandesh=E:/Keystore/pharma.keystore
storeFileSunil=/Users/abc/Downloads/pharma.keystore
storeFile=G:/keystore/pharma.keystore